### ISSUE TITLE
AttributeError: module 'serial' has no attribute 'Serial'

### ISSUE THREAD

**Issue by jeremy-collette** [jeremy-collette/smartpianoclient-python#2]
README instructions describe installing "serial" module, but "pySerial" is actually required.

Missing pySerial library causes following error:

> AttributeError: module 'serial' has no attribute 'Serial'

**Comment by jeremy-collette** [comment]
pySerial can be installed by running:

`pip3 install pyserial`

**Comment by firtinahg** [comment]
First uninstall  serial module -> "sudo pip3 uninstall serial" then install pyserial module "sudo pip3 install pyserial". It will work.

**Comment by beachbum975** [comment]
I believe I have a slight improvement on the "serial has no attribute Serial" issue.  While it is true that having mistakenly installed "serial" instead of "pyserial" is the source of the problem, some users have probably installed both, and the system may have confounded the two apps.  It is necessary to uninstall not only serial but also pyserial from your python version.  Then reinstall pyserial and the problem will be solved.
